name: Deploy Docker Image to AWS

on:
  workflow_run:
    workflows: ['Publish Docker Image']
    types: [completed]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Stop the old container
        run: docker stop university-management-auth-service || true
      - name: Remove the old Container
        run: docker rm university-management-auth-service || true
      - name: Remove the old Image
        run: docker rmi ${{secrets.DOCKERHUB_USERNAME}}/university-management-auth-service:latest || true
      - name: Pull image from Docker Hub
        run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/university-management-auth-service:latest
      - name: Run the Image with Port Configuration
        run: docker compose up -d
