name: Deploy Docker Image to AWS

on:
  workflow_run:
    workflows: ['Publish Docker Image']
    types: [completed]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Stop the old container
        run: university-management-auth-service || true
      - name: Delete the old Container
        run: docker rm  university-management-auth-service || true
      - name: Delete the old Image
        run: docker rmi  ${{secrets.DOCKERHUB_USERNAME}}/university-management-auth-service:latest || true
      - name: Pull image from docker hub
        run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/university-management-auth-service:latest
      - name: Run the Image
        run: docker-compose -f docker-compose.yml up -d
