name: Publish Docker Image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: echo "${{secrets.DOCKERGUB_TOKEN}}" | docker login -u "${{secrets.DOCKERGUB_USERNAME}}" --password-stdin

      - name: Checkout Code
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERGUB_TOKEN}}/university-management-auth-service:latest
